#!/usr/bin/env python3
"""
Test script for Paper Generation Agent
Tests LLM connectivity and basic generation
"""

import sys
import os

# Add app directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

from services.paper_generation_agent import PaperGenerationAgent


def test_llm_availability():
    """Test which LLM services are available"""
    print("=" * 60)
    print("🔍 Testing LLM Availability")
    print("=" * 60)
    
    agent = PaperGenerationAgent()
    availability = agent.check_llm_availability()
    
    available_count = sum(1 for v in availability.values() if v)
    
    print(f"\n✓ {available_count}/3 LLM services available")
    
    if available_count == 0:
        print("\n❌ No LLM services available!")
        print("\nPlease set at least one API key in .env file:")
        print("  - GROQ_API_KEY")
        print("  - GEMINI_API_KEY")
        print("  - HUGGINGFACE_API_KEY")
        print("\nSee AGENT_SETUP_GUIDE.md for instructions")
        return False
    
    return True


def test_single_paper_generation():
    """Test generating a single paper"""
    print("\n" + "=" * 60)
    print("📄 Testing Single Paper Generation")
    print("=" * 60)
    
    agent = PaperGenerationAgent()
    
    # Test parameters
    grade = "8"
    subject = "Maths"
    topic = "Basic Algebra"
    
    print(f"\nTest: Grade {grade} | {subject} | {topic}")
    print("Generating 1 paper as a test...\n")
    
    # Check availability first
    availability = agent.check_llm_availability()
    
    # Try to generate one paper
    paper = agent.generate_single_paper_with_fallback(
        grade, subject, topic, 1, availability
    )
    
    if paper:
        print("\n✅ Test paper generated successfully!")
        print(f"   Questions: {len(paper.get('questions', []))}")
        print(f"   Generated by: {paper.get('generated_by', 'unknown')}")
        return True
    else:
        print("\n❌ Failed to generate test paper")
        return False


def test_parallel_generation():
    """Test parallel generation of 3 papers"""
    print("\n" + "=" * 60)
    print("🚀 Testing Parallel Generation (3 Papers)")
    print("=" * 60)
    
    agent = PaperGenerationAgent()
    
    # Test parameters
    grade = "8"
    subject = "Maths"
    topic = "Algebra Test"
    
    print(f"\nTest: Grade {grade} | {subject} | {topic}")
    print("Generating 3 papers in parallel...\n")
    
    papers = agent.generate_papers_parallel(grade, subject, topic)
    
    if papers and len(papers) > 0:
        print(f"\n✅ Successfully generated {len(papers)}/3 papers!")
        for i, paper in enumerate(papers, 1):
            print(f"   Paper {i}: {len(paper.get('questions', []))} questions "
                  f"(by {paper.get('generated_by', 'unknown')})")
        return True
    else:
        print("\n❌ Failed to generate papers")
        return False


def main():
    """Run all tests"""
    print("\n🤖 Paper Generation Agent - Test Suite")
    print("=" * 60)
    
    # Test 1: Check LLM availability
    if not test_llm_availability():
        print("\n❌ Cannot proceed without at least one LLM service")
        sys.exit(1)
    
    # Ask user which test to run
    print("\n" + "=" * 60)
    print("Select test to run:")
    print("=" * 60)
    print("1. Quick test (1 paper)")
    print("2. Full test (3 papers in parallel)")
    print("3. Both tests")
    print("0. Exit")
    
    choice = input("\nEnter choice (0-3): ").strip()
    
    if choice == "1":
        test_single_paper_generation()
    elif choice == "2":
        test_parallel_generation()
    elif choice == "3":
        test_single_paper_generation()
        test_parallel_generation()
    else:
        print("\nExiting...")
        return
    
    print("\n" + "=" * 60)
    print("✅ Testing Complete!")
    print("=" * 60)
    print("\nIf tests passed, you're ready to use the agent in the main app!")
    print("Run: python app/main.py")
    print("")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Test interrupted by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
